[tool.poetry]
name = "viral-marketing"
version = "0.1.0"
description = "Viral marketing Django project for team 6"
authors = ["oz team6 <team6@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.2.7"
djangorestframework = "^3.16.1"
django-environ = "^0.12.0"
drf-spectacular = "^0.28.0"
djangorestframework-simplejwt = "^5.5.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.0"
pytest = "^8.4.2"
factory-boy = "^3.3.3"
black = "^24.0.0"

[tool.poetry.group.prod.dependencies]
gunicorn = "^23.0.0"
psycopg2-binary = "^2.9.11"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP"]
ignore = ["D", "ANN", "E501"]

[tool.ruff.lint.isort]
known-first-party = ["config", "apps"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
