[project]
name = "viral-maketing"
version = "0.1.0"
description = ""
authors = [
    {name = "han-son-03",email = "rkdgksths11@naver.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "django (>=5.2.7,<6.0.0)",
    "djangorestframework",
    "django-environ (>=0.12.0,<0.13.0)",
    "drf-spectacular (>=0.28.0,<0.29.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.0"
pytest = "^8.4.2"
factory-boy = "^3.3.3"


[tool.poetry.group.prod.dependencies]
gunicorn = "^23.0.0"
psycopg2-binary = "^2.9.11"

