# Generated by Django 5.2.7 on 2025-10-15 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('admin', '관리자'), ('user', '사용자'), ('guest', '손님')], default='user', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 거래내역',
                'verbose_name_plural': '사용자 거래내역 목록',
                'db_table': 'transaction_history',
            },
        ),
    ]
