# Generated by Django 5.2.7 on 2025-10-15 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('transaction', '거래'), ('low_balance', '낮은 잔액'), ('goal', '목표'), ('system', '시스템')], max_length=20)),
                ('channel', models.CharField(choices=[('in-app', '앱 안에서'), ('email', '이메일'), ('both', '둘 다')], default='in-app', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('condition_value', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_active', models.BooleanField(default=False)),
                ('is_triggered', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
